import React from 'react'

function TermsOfUse() {
  return (
    <div className="container">
  <div className="howitworks"> 
    <div className="hero-text" style={{"padding":"20px"}}>
      <div className="row">
        <div className="offset-md-3 col-md-6">
          <div className=" about-title " style={{"margin-top":"25px"}}>
            <h1 className="about-text1 ">Terms of Use</h1>
          </div>
        </div>
        <div className="col-md-12" style={{"margin-top":"0px","padding":"10px"}}>
          <div className="about-content">
            This Website is owned and managed by LoanTark. The company heads their operations atLoan tark HSG. Sty. Ltd ., Shop No.10, Building No.10, Kamgarnagar 400024 Kurla East, Maharashtra, India. The "Operator", “We”, “Us” are authorized to exercise the ownership and intellectual property rights to the Website.<br /><br />
            People (the "Users" or individually a "User" or "You" or "Your") visiting our website www.loantark.org or any other web/ mobile application of LoanTark (such website and/ or web/ mobile applications referred to as the "Website" or “Site”) are required to get themselves aquainted to the terms of use before using the website. Access to and use of the Website by a User is deemed to represent that the user has thereby agreed to our terms and conditions of using the website to the sole purpose of what the site has been built in for. In case a User disagrees with these terms &amp; conditions (as may be amended from time to time), he/she shall leave the Site and refrain from visiting it in the future. The user has no right to rumor false beliefs regarding the website. The website has been built for the sole purpose of helping the needy.<br /><br />
            This Policy on Website Use regulates the rights and obligations of the Manager (Us) and the Users (You) regarding the use of the Website. User is requested to read these Terms of Use carefully before registering, accessing, browsing through our website. This is a legally binding agreement between the User and the Manager (Us). By this we try to regulate the norms under which the user can access the website for his needs. In the event of any conflict between the terms and conditions of specific products and services and these Terms of Use, the conditions specific to such products and services shall prevail. It is believed that User (You) understands that there exists no partnership, employment between the User (You) and the Manager (Us) on account of using this website.<br /><br />
            <b>Use of Information and Materials</b><br /><br />
            The Content contained in this Website, including the text, any internal or external links to other websites, design etc are subject to copyright. The visitor of the website has no right to copy the contents of the website under any circumstances for their leisure. To use the content of the website for their own use, the user need to have a written consent from the website's Manager (Us) User should not copy, download, publish, distribute or reproduce any of the Content contained on this Website in any form without prior permission of the Operator. <br /><br />
            The Content (text, design, data, news items, software, images, video and audio etc.) contained on this Website is provided for general information only. The visitor has no right to use it as a basis for making business/commercial decisions. User is advised to exercise due caution and/or seek independent advice before entering into any arrangement or financial obligation based on the Content contained on this Website.<br /><br />
            <b>Creation of User Account for availing Services</b><br /><br />
            To avail personal loans other services from LoanTark, the User has to create an account (“User Account”) with us by registering himself / herself. It is believed that user understands that the user is solely responsible for maintaining the secrecy of his registered user id and the password. The User shall be responsible for all activities that occur in connection with your User Account. In any case of unauthorize use of your account, the user needs to convey this to the company, so that appropriate action may be taken on time to avoid any harm. The user is advised not to create multiple accounts in his/her/other's name. The user shall not use your User Account for any purpose that is unlawful, illegal or forbidden by law. As a consideration for availing Loan/ Service through Website, you may be required to pay certain fee, charges, interest or cost as may be applicable as mentioned in our Website or as per the terms for respective products and services as prescribed by us. We beleive that you understand that application of loan through online means is dependent on technical factors which includes your internet connectivity, your ability to make payment through online means which in-turn is depended on payment services from your bank or similar service providers, capability of the computer or phone which you use for the purpose, your careful approach in reading the terms, understanding the same and following the process. You are soley responsible prevention and back up of data and/or equipment. The user should take it as a reasonable responsibility to scan their computer for any computer viruses. We make no representations or warranties regarding the accuracy, functionality or performance of any third party software that may be used in connection with the Website.<br /><br />
            <b>For the purpose of creating the User Account through the Website:</b><br /><br />
            1.You should hold Indian citizenship and have attained a minimum age of 18 years.<br />
            2.You have valid email address and valid mobile number. Having a valid mobile number is madatory as we would be sending you an OTP which is needed in order to get you registered at LoanTark.<br />
            3.You need to have an updated UID (Aadhaar) number and Permanent Account Number (PAN) or such other valid identity proof and residential address proof as described by Reserve Bank of India and prescribed by us for KYC requirements<br />
            4.You need to have a bank account in India (bank name, IFSC, branch and account number). The account should have enabled internet banking facility for the purpose of transfer of funds.<br />
            5.You should not be the person who is prohibited by any means, due to any reasons from availing loan from us.<br />
            6.You shall not impersonate any person or entity or falsely state or otherwise misrepresent age, identity or affiliation with any person or entity.<br />
            7.You should be either salaried employee (government employee or a private employee) or a self-employed indiviual.<br />
            8.You have read and understood the Privacy Policy, Policy on Website Use as well as General Terms and Conditions for obtaining Personal Loan from LoanTark.<br /><br />
            While creating the User Account you will be asked to provide certain information which may include your KYC Details, Personal Details, Loan Details, and Bank Details which is collectively referred to as Customer Data. It is our kind request to you to kindly provide rightful information to increase our credibility. You need to make sure that the details entered by you are correct to your best knowledge. We can rely on it for providing the Loan and/or services sought by you through the Website.<br /><br />
            In conformity with you creating the User Account and submitting User Data, We will be holding and processing the data. The data you have submitted with us is subject to proper scrutiny by our authorized officials. You grant us authority to use the same for the purposes as described in "Privacy Policy of LoanTark" as amended from time to time. You are notified that the User Data may be used for reporting to Credit Information Companies under the Credit Information Companies (Regulation) Act, 2005 ("CIC Act"), credit service organization for analytical purpose, Central Know Your Customer data registries and other KYC repository services, data storage agencies which may be third party service providers, financial institution, Reserve Bank of India, any other authority (including Unique Identification Authority of India) or any third party engaged by Operator for purpose of proper verification and assessment and scrutinization of the Data, for statistics regarding User’s Account, to satisfy any legally enforceable process or compliance purpose, detecting and protecting against error, fraud or identification of other criminal activity or for archiving User Data and for complying with the laws applicable from time to time, in India or abroad (as may be decided by LoanTark from time to time). Your usage of the Website shall be deemed as consent to the aforesaid and this is without prejudice to other terms mentioned hereof or incorporated here by way of any reference.<br /><br />
            Apart from accepting this Policy on Website Use for availing the loan from LoanTark, you shall be additionally required to agree ‘General Terms and conditions for obtaining Personal Loan LoanTark' as registered with Sub-Registrar of Assurances at Mumbai (Maharashtra) under the Deed of Declaration having Registration No.23050 dated 10.11.2015 (hereinafter referred as "GTC") for terms and conditions applicable to the loan Further, it is made clear that accepting these terms or creation of User Account will not bind us in granting you any loan or services, the same shall be further governed by the specific terms in addition to this Policy.<br /><br />
            <b>Links to Other Sites</b><br /><br />
            The Website may contain certain links to other external websites that are not under the Manager's (Us) control. In such cases, it is advisable to read the terms &amp; conditions of their website. Specifically, the Manager (Us) does not assume any responsibility for any obligations of any persons who offer, provide or mediate services or goods on such sites. The Manager is neither responsible for the policies and practices of other companies nor for the contents of linked third-party sites. We recommend the User to read the privacy policy and terms of use of such website to find out how they protect the User’s Customer Data.<br /><br />
            <b>Prohibited Conduct</b><br /><br />
            By using our Website you agree that you shall not:<br /><br />
            (a) contravene ours or any third party's intellectual property rights, rights of publicity or privacy;<br />
            (b) use our Website for spamming, or rumoring false beliefs, or illegally interferring with security, integrity, networks of operation related features of our Website or features that enforce limitations on the use of Website;<br />
            (c) refuse to cooperate in an investigation, this may invole failing to provide us with identity confirmation or proof or any other information that you have provided us with.<br />
            (d) post any message, image or program which is negative and that violates any law or which may fall under any kind of negative propoganda, or which is libellous, defamatory or which discloses private or personal matters concerning an individual;<br />
            (e) upload any content that constitutes remiss advice or contains any remiss statement or instructions by an individual, which may promote riots, any kind of criminal activity; or any content which is in contempt of any court, or in breach of any court order or any law.<br />
            (f) use the facilities and capabilities of Site to conduct any activity that is illegal in any form.<br />
            (g) breach these Terms or any other policies which we have; and<br />
            (h) use web site to collect or obtain personal information, including without limitation, personal information about other users of our Site.<br /><br />
            <b>Copyrights and Trademarks</b><br /><br />
            The user of the website have no right to use any of our trade names, trademarks, service marks, logos, domain names, and other distinctive brand features. Alternatively, you do not have the right to remove, obscure, or alter any proprietary rights notices (including trademark and copyright notices), which may be affixed within the services. We does not warrant that your use of materials displayed at the Site will not contravene rights of any third party
            All copyright and all intellectual property rights in all material presented on the Site (including but not limited to text, video or images), trademarks and logos appearing on this site are the property of the Manager (Us). The Content contained in this Website, including the text, any internal or external links to other websites, design etc are subject to copyright. The visitor of the website has no right to copy the contents of the website under any circumstances for their leisure.
            <br /><br />
            <b>Violation of the Terms of Use</b><br /><br />
            Without prejudice to our rights under this Policy, if you violate these terms &amp; conditions and in any way, or if we suspect that you have breached these terms &amp; conditions of Website use in any way, we may (i) send you one or more formal warnings; (ii) temporarily suspend your services to the website; (iii) permanently prohibit you from using our services; (iv) block the device using the IP address or International Mobile Equipment Identity Number from accessing Website; (v) contact any or all of your internet service providers and request that they block your access, make the website unavailable to you; (vi) Indulge into having taken a legal action against you, whether for violation of terms of use or recovery of amounts due or damages or otherwise; and/or (vii) suspend or delete your account on Website.
            <br /><br />
            <b>No Warranty and Limitation of Liability</b><br /><br />
            This Website may contain opinions and statements of various professionals/ experts/ analysts, etc. Manager of the website (Us) does not represent/ endorse the accuracy, reliability of any of the opinions or statements. The Manager (Us) does not guarantee the correctness, accuracy, completeness, or availability of this Website's contents and/or services and does not accept any responsibility (e.g. towards the Users of the Website) in this respect. We therefore advice the users to themself verify the opinions or statements in terms of their correctness, accuracy, availability etc. <br /><br />
            The User is fully liable for any risk for his use of this Site and the Manager (Us) does not assume any responsibility or liability for such risk. LoanTark, its subsidiary companies, their directors and employees accept no liability and will not be responsible for any loss or damage arising directly or indirectly from use of this Website by any User or any linked site or inability to use by any party, howsoever arising. This may include any loss, damage or expense arising from, but not limited to, any defect, error, omission, interruption, imperfection, fault, mistake or inaccuracy with this Website, its Contents or associated services.<br /><br />
            No information sent to any customer through this Website shall involve any warranty by the Manager (Us), or its subsidiaries or affiliates regarding the credit-worthiness, financial performance or prospects, solvency, or viability of any company or other legal entity or the business carried on by such entity.<br /><br />
            By accepting this terms or using this Website or by expressing intent or by making application for availing any loan or services, you confirm that you have understood the intricacies, the related risks and the process, you also confirm the aspects mentioned aforesaid are beyond control of the Operator. Hence, any of your acts will be at your choice and discretion and therefore you disclaim us from claim or damages suffered by you or for loss of profit.<br /><br />
            Due to the nature of the Internet transactions, use of or access to the Website may be subject to interruption, transmission blackout, delayed transmission and incorrect data transmission. The Operator is not liable for malfunctions in communications facilities not under its control that may affect the accuracy or timeliness of messages and transactions you send.
            <br /><br />
            <b>Changes made to the Website</b><br /><br />
            The Manager (Us) has the right to alter the contents, appearance, accessibility of the website as when needed, without prior notice. The publication of any data or information on the Website, with the exception of this Policy on Website Use, will not be considered as an act in law, unless expressly stated otherwise.
            <br /><br />
            The User is expected to keep updated of any changes made in this Website and the information available on it on a regular basis. The Manager (Us) enrolls no responsibility about informing the user about the changes being made to the website. Though Operator will endeavor to ensure that information contained on this Site is obtained from sources which, it feels, are reliable. Operator does not warrant such information’s completeness or accuracy. Use of the Website after the republication of amended Policy is deemed to represent the User's consent with the amended Policy on Website Use.
            <br /><br />
            <b>Dispute Resolution</b><br /><br />
            The use of this Website and the Policy on Website Use shall be governed by Indian law. The Policy on Website Use and your activity under this Policy are an ‘electronic record’ in accordance with the (Indian) Information Technology Act, 2000.<br /><br />
            Any dispute arising in connection with the use of Website shall be settled before courts of Maharashtra (India) and in accordance with Indian law. Should any provision of this Policy be held invalid or unenforceable for any reason, the invalid or unenforceable provision shall be severable from the remaining provisions and shall not affect the validity or enforceability thereof.<br /><br />
            <b>Annual Percentage Rate(APR)</b><br /><br />
            APR or Annual Percentage Rate is a very common term in the banking world. Though common, this term might result in confusion for the first-time loan borrowers. This is an interest rate that is different from the standard rate of interest and that is why an applicant must have a good amount of knowledge about APR before opting for a personal loan. Only when you understand the different types of interest rates that you have to pay annually, you can enjoy the best advantages of availing a loan.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  )
}

export default TermsOfUse